.TH daemon "noxnet terminal client" "2015-05-15" "version 1.0"

.SH NAME
client_console - a cli client for a noxnet deamon

.SH SYNOPSIS
.BI "client_console " [client_port]

.SH DESCRIPTION
This program is used in
.I noxnet
as a client for interfacing with a noxnet deamon. To send commands to the daemon,
the client and deamon need to communicate over the same port.

.SH OPTIONS
.IP client_port
Set the value of the port to communicate with the daemon to
.IR client_port .

.SH SEE ALSO
.BR daemon (1) 
