#!/bin/sh 
build=$(cat ../noxnet.pro.user | grep ProjectExplorer.BuildConfiguration.BuildDirectory |grep Debug |cut -f2 -d'>' | cut -f1 -d'<')
cd $build/src/daemon

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi

./daemon -p $((8000 + $1)) -c $((9000 - $1)) -d database$1.db -a /tmp/arena$1 &
